name: Copy badges to server
description: To copy badges to server
inputs:
  app-name:
    description: Name of the App
    required: true
  badge:
    description: Badge for main branch
    required: true


runs:
  using: "composite"
  steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.1

      - name: Copy badge to server
        shell: bash
        env: 
          BADGE: ${{ inputs.badge }}
        run:  |
          REPO_NAME="${{ github.event.repository.name }}"
          rm /mnt/samba/$REPO_NAME/${{ inputs.app-name }}-main.svg  2> /dev/null || true # to avoid permissions issue, remove main files first 
          curl -L $BADGE -o "/mnt/samba/$REPO_NAME/${{ inputs.app-name }}-main.svg"